version: '3'

services:
  backend:
    build:
      context: ./back-end # where the dockerfile for back-end is located
    ports:
      - '5252:5252' # port 5252 from the host to 5252 in the container
    depends_on:
      - frontend # frontend is started before the 'backend' service

  frontend:
    build:
      context: ./front-end # where the dockerfile for front-end is located
    ports:
      - '9000:9000' # port 9000 from the host to port 9000 in the container
