version: '3'

services:
  backend:
    build:
      context: ./back-end # where the dockerfile for back-end is located
      dockerfile: Dockerfile # dockerfile to use
    ports:
      - '5050:5000' # port 5050 from the host to 5000 in the container
    depends_on:
      - frontend # frontend is started before the 'backend' service

  frontend:
    build:
      context: ./front-end # where the dockerfile for front-end is located
    ports:
      - '80:80' # port 80 from the host to port 80 in the container