version: '3'

services:
  backend:
    build:
      context: ./back-end # where the dockerfile for back-end is located
    depends_on:
      - frontend # frontend is started before the 'backend' service

  frontend:
    build:
      context: ./front-end # where the dockerfile for front-end is located

  proxy:
    build:
      context: ./proxy # where the dockerfile for proxy is located
    image: task5-proxy
    ports:
      - '80:80' # map the container's port 80 to the host machine's port 80
    depends_on:
      - frontend
      - backend

